//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParqueoUlacit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraParqueo
    {
        public int BitacoraID { get; set; }
        public Nullable<int> VehiculoID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string TipoMovimiento { get; set; }
        public Nullable<bool> EstadoIngreso { get; set; }
        public string NumeroPlaca { get; set; }
    
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
