//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParqueoUlacit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraParqueo
    {
        public int BitacoraID { get; set; }
        public Nullable<int> VehiculoID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string TipoMovimiento { get; set; }
        public Nullable<bool> EstadoIngreso { get; set; }
        public string NumeroPlaca { get; set; }
        public Nullable<int> ParqueoID { get; set; }
    
        public virtual Vehiculo Vehiculo { get; set; }
        public virtual Parqueo Parqueo { get; set; }
    }
}
