//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParqueoUlacit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parqueo
    {
        public Parqueo()
        {
            this.Vehiculo = new HashSet<Vehiculo>();
        }
    
        public int ParqueoID { get; set; }
        public string Nombre_Parqueo { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<int> Espacios_Carros { get; set; }
        public Nullable<int> Espacios_Moto { get; set; }
        public Nullable<int> Espacios_Ley7600 { get; set; }
    
        public virtual ICollection<Vehiculo> Vehiculo { get; set; }
    }
}
