//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParqueoUlacit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Vehiculoes = new HashSet<Vehiculo>();
        }
    
        public int UsuarioID { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Identificacion { get; set; }
        public string Clave { get; set; }
        public Nullable<bool> ClaveCambiada { get; set; }
        public Nullable<int> RolID { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual ICollection<Vehiculo> Vehiculoes { get; set; }
    }
}
