//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParqueoUlacit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public Vehiculo()
        {
            this.BitacoraParqueo = new HashSet<BitacoraParqueo>();
            this.IntentosIngresoFallidos = new HashSet<IntentosIngresoFallidos>();
        }
    
        public int VehiculoID { get; set; }
        public string Marca { get; set; }
        public string Color { get; set; }
        public string NumeroPlaca { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public Nullable<bool> UsaEspacioLey7600 { get; set; }
        public string Estado { get; set; }
        public Nullable<int> ParqueoID { get; set; }
    
        public virtual ICollection<BitacoraParqueo> BitacoraParqueo { get; set; }
        public virtual ICollection<IntentosIngresoFallidos> IntentosIngresoFallidos { get; set; }
        public virtual Parqueo Parqueo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
